### ISSUE TITLE
`onValueChange` stops working after returning `undefined`

### ISSUE THREAD

**Issue by lochie** [pacocoursey/cmdk#106]
Looks like `<Command onValueChange={...} />` stops firing after a returned `undefined` when no result is found in the search query.

Can be seen on this example where the right side examples stop appearing:

https://user-images.githubusercontent.com/1930210/227848919-3aee079f-9529-41a1-9a55-e1a8ebb035ac.mp4

**Comment by ajhaupt7** [comment]
I was able to get this working by adding the `value` and `onValueChange` props to `Command.Input` rather than `Command`. The docs are confusing as they seem to indicate the ability to add these props to the root or to the input.

**Comment by jeloi** [comment]
@ajhaupt7 note that doesn't achieve the exact same thing - onValueChange for Command.Input will have the exact input text entered, whereas the `Command` onValueChange is triggered with the selected value (set by Command.Item's param)
