### ISSUE TITLE
Generated items not showing up when erasing

### ISSUE THREAD

**Issue by Joel-Jensen** [pacocoursey/cmdk#172]
Looks like everything works fine when items are hardcoded but when they are generated from an array or similar it does not work. 

**Fastest way to replicate is to:**
1. Go to https://cmdk.paco.me/.
2. Search for "caste" in raycast, erase one letter at a time and watch how programs pop up.
3. Now go to Vercel
4.  Search for "projecte", you now need to erase everything before you can see anything at all.

And if you print the values
```js
filter={(value, search) => {
  console.log(value, search)
  if (value.includes(search)) return 1
  return 0
}}
```
You can see that it's not executed anymore once something is filtered out. So seems like the internal data structure doesn't know what options there are when it's not hardcoded.

**Comment by andrebrito16** [comment]
Facing the same issue here!

**Comment by dschlabach** [comment]
Having this issue as well

**Comment by dschlabach** [comment]
Did some investigating to see what was going on under the hood. This bug only seems to happen when "value" is not explicitly set.

In such cases, `useValue` attempts to set the value to the `textContent` of the rendered component. But once an option is filtered out of the list, it is dropped from the DOM. Thus, there is no `textContent` to match against, until the input is "" and this reset is triggered:

```
  function filterItems() {
    if (
      !state.current.search ||
      // Explicitly false, because true | undefined is the default
      propsRef.current.shouldFilter === false
    ) {
      state.current.filtered.count = allItems.current.size
      // Do nothing, each item will know to show itself because search is empty
      return
    }``` 


<img width="1003" alt="CleanShot 2023-08-30 at 12 43 53" src="https://github.com/pacocoursey/cmdk/assets/31226559/76aa94a2-072f-4fd6-83f3-5d71cccd91de">

**Comment by SecretKeeper** [comment]
same issue here , any updates?

**Comment by dschlabach** [comment]
Wasn't able to fix this myself due to time constraints. I'd suggest setting value explicitly for now until there's a workaround

**Comment by Joel-Jensen** [comment]
Works now, thank you @dschlabach and @WITS! 🙌

**Comment by mauliksoni110** [comment]
@Joel-Jensen How to use the fix? I see it's not released yet.

**Comment by Joel-Jensen** [comment]
@mauliksoni110 Sorry not sure since it's a subdir. Only tested it on the https://cmdk.paco.me/ page and currently waiting for the official release build.

**Comment by dschlabach** [comment]
I just copied the contents of /src into my repo for now rather than importing from the library
