### ISSUE TITLE
Why can not use type=search for Command.Input

### ISSUE THREAD

**Issue by zecka** [pacocoursey/cmdk#175]
I try to implement a **cross icon** into the Command.Input (to reset the input content wihtout leaving focus).
Something like:

![image](https://uploads.linear.app/91703e7f-9f89-43cc-9456-60ec4f6eeb96/214c9bf5-77e0-4589-9d7c-ad8da51fb0f2/f7594add-c95f-4476-81c3-b4dfe82a7aef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzkxNzAzZTdmLTlmODktNDNjYy05NDU2LTYwZWM0ZjZlZWI5Ni8yMTRjOWJmNS03N2UwLTQ1ODktOWQ3Yy1hZDhkYTUxZmIwZjIvZjc1OTRhZGQtYzk1Zi00NDc2LTgxYzMtYjRkZmU4MmE3YWVmIiwiaWF0IjoxNzE2MjgwNTgzLCJleHAiOjMzMjg2ODQwNTgzfQ.QtxHU7CXYEmlI_DPvUVQVA036BZB-IYgzWBrvmPH1QQ)

But type attribute seems to be Omit from Command.Input component [(check /src/index.tsx#L51)](https://github.com/pacocoursey/cmdk/blob/main/cmdk/src/index.tsx#L51)

Is there any particular reason why the type is omitted from InputProps?

What do you suggest to implement the cross icon ?

edit: maybe this topic should be moved to discussion, but don't know how to move it :(

**Comment by mardausdennis** [comment]
This feature would be useful. I was wondering if there have been any updates or further discussions on this topic?

**Comment by TheMikeyRoss** [comment]
@pacocoursey

**Comment by steve-marmalade** [comment]
Came here looking for the same. I would like to customize the icon being displayed on smartphone keyboards by specifying `type="search"`
