### ISSUE TITLE
Export default filter function from package

### ISSUE THREAD

**Issue by stonix26** [pacocoursey/cmdk#197]
Does this support `react-virtuoso` ?

I have created a little demo. It renders properly, but when I try to enter in the input/search field, it fires an error `Node.appendChild: Argument 1 is not an object.`

[https://stackblitz.com/edit/stackblitz-starters-nekqj6?file=src%2FApp.tsx](https://stackblitz.com/edit/stackblitz-starters-nekqj6?file=src%2FApp.tsx)

**Comment by inokawa** [comment]
Hi, it's not react-virtuoso but https://github.com/inokawa/virtua will work with cmdk. It has similar functionality to react-virtuoso and 3x lighter.

https://inokawa.github.io/virtua/?path=/story/advanced-with-cmdk--default
https://github.com/inokawa/virtua/blob/main/stories/react/advanced/With%20cmdk.stories.tsx

**Comment by kristofdombi** [comment]
You can use it with Virtuoso. you need to disable the default filtering (`shouldFilter={false}`) and provide a custom filter.
See [here](https://stackblitz.com/edit/stackblitz-starters-iaovtf?file=src%2FApp.tsx).

**Comment by arjendevos** [comment]
@kristofdombi would be nice if the filtering is exported from this package

**Comment by pacocoursey** [comment]
Agreed, I'll add an export for the defaultFilter. A future version may not ship with a default filter at all, to reduce bundle size.
