### ISSUE TITLE
Minify output better

### ISSUE THREAD

**Issue by pacocoursey** [pacocoursey/cmdk#2]
The library size can be minified by mangling object properties like `.filtered`. I think https://github.com/vercel/swr uses some tricks for this, like exporting things from barrel files or using TS enums.

Also, we could consider splitting `cmdk` and `cmdk/dialog` so that the ~fairly large Radix Dialog dependency isn't an upfront cost. Though I'd imagine most people want to use this library in the context of a dialog.

**Comment by lilingxi01** [comment]
It also makes sense that some people may want to embed the command window inside a page. Separating the dialog module can give users more flexibility on choosing the command window container.

**Comment by pacocoursey** [comment]
@lilingxi01 `Command` by default already gives you that flexibility. For example, you can put it inside a Popover.

**Comment by sherwinyu** [comment]
> Why minify the output? I am trying to debug an issue and it's almost impossible because all variable names are minified
> 
> Minification should be responsability of the final bundler, not of the library

I'm encountering this also -- did you find any workaround @remorses ?
