### ISSUE TITLE
feat: allow overwriting props

### ISSUE THREAD

**Issue by gylxan** [pacocoursey/cmdk#201]
There are many cases where it makes sense to override the props of the components.

Examples:
- `aria-label` of e.g. `CommandLoading` and `CommandList` to support multi language
- `aria-expanded` of `CommandInput`, which is always `true` currently, but should only be `true`, when the input has focus or after typing, when the list is shown 
- `type` of `CommandInput` to let users only insert numbers  for instance

There is already a PR for it  #117, but I created a new one #202 

Here is a [code sandbox](https://codesandbox.io/p/devbox/cmdk-with-props-lz4dg7), where we can see the problem

Maybe we can realize it?

**Comment by MatchuPitchu** [comment]
Would be very useful.

**Comment by albertAS61** [comment]
Glad to see @gylxan that someone also pick up the topic with overwriting props. For me the most important part is with type of command input. Topic also arise in #175 and for me the crucial part with changing type is that on mobile I can force browser to use specific type of keyboard :)
