### ISSUE TITLE
The latest version of npm does not contain the latest updates from github

### ISSUE THREAD

**Issue by jtapeg** [pacocoursey/cmdk#215]
Package version on npm 0.2.1, does not contain the keyword addition update

**Comment by Arinji2** [comment]
A workaround i did was this
`
value={doc.name+" "+doc.keywords?.join(" ")}
`

It seems to work.

**Comment by osnoser1** [comment]
Yees, I need the asChild prop that is available only in the main branch 🙈

**Comment by nklhtv** [comment]
@pacocoursey Should we expect npm version bump soon?

**Comment by pacocoursey** [comment]
https://github.com/pacocoursey/cmdk/releases/tag/v1.0.0
