### ISSUE TITLE
Change the selection key

### ISSUE THREAD

**Issue by MIKTHATGUY** [pacocoursey/cmdk#216]
Hi I’m developing a command line-like application and I was trying to change the key for the selection from ENTER to TAB is there a way?
I'm kind of new to html - js - react so any suggestion is very welcome.

**Comment by pacocoursey** [comment]
Hihi, currently not possible, Enter is always used. I'm considering this a feature request.

**Comment by MIKTHATGUY** [comment]
> Hihi, currently not possible, Enter is always used. I'm considering this a feature request.

Ty very much it would be really useful
