### ISSUE TITLE
Escape " (quote) in the command item text

### ISSUE THREAD

**Issue by yjl9903** [pacocoursey/cmdk#222]
The following querySelectorAll will throw error when `data-value="..."` string contains " (quote)

https://github.com/pacocoursey/cmdk/blob/eb4fd0fdf39caf532bb2ae7deaa969dadb607150/cmdk/src/index.tsx#L399-L404

Maybe can encodeURI like this?

https://github.com/pacocoursey/cmdk/blob/eb4fd0fdf39caf532bb2ae7deaa969dadb607150/cmdk/src/index.tsx#L772-L777

**Comment by Rinava** [comment]
This error still happens

**Comment by yjl9903** [comment]
@Rinava Any minimal reproduction?
