### ISSUE TITLE
bug (?): scroll position inside list is not reset when clearing the list

### ISSUE THREAD

**Issue by jimniels** [pacocoursey/cmdk#234]
I'm not sure if this is intended behavior, but when you filter down the list to an item that's near the bottom of the list, then clear your search filter, all the results return but the scroll position of the list is not reset to the top.

Take a look at the example from the project's home page:

- Switch to Vercel example
- (Note that the last item in the list is "Contact Support")
- Ensure the list scrolled to the top
- Type in "Contact" and see the list filtered down to a single item
- Select all text in the input box and delete it
- See that "Contact" is on-screen (and the scroll position of the list is not back at the top, where it was when you started filtering your results)

https://github.com/pacocoursey/cmdk/assets/1316441/02e688f8-725b-4606-9506-ecadfbbddbea

This seems unexpected to me. Whenever I clear my search query, I expect to the scroll position of the results list to always be reset to the top of the list.

**Comment by triptu** [comment]
workaround i'm using for this -

```tsx
const listRef = useRef<HTMLDivElement>(null);

const scrollUpWhenCleared = useCallback((value: string) => {
    if (value === "") {
      requestAnimationFrame(() => {
        listRef.current?.scrollTo({ top: 0 });
      });
    }
  }, []);

<Command.List ref={listRef}>

<Command.Input  onValueChange={scrollUpWhenCleared} >...

```

https://github.com/pacocoursey/cmdk/issues/233 looks similar.
