### ISSUE TITLE
Command Items disabled under CommandList

### ISSUE THREAD

**Issue by ezraanglo** [pacocoursey/cmdk#236]
Hi! First I wanna thank you for this library! It's been a time saver for me ~

So I just upgraded to the latest version and I'm using shadcn/ui. 
I don't know if its just me but the command items are disabled after the update. 

I can see the CommandList is now required on the new version. Maybe I'm missing some props to have them enabled? Really appreciate any help!

**Comment by nenya1840** [comment]
+1

**Comment by nenya1840** [comment]
in your project components/ui/command.tsx

can change from
`data-[disabled]:pointer-events-none data-[disabled]:opacity-50`
to
`data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50`

**Comment by tgdn** [comment]
Thanks!

**Comment by pacocoursey** [comment]
Yep, thanks. I'll add a note to the release notes because this is technically a breaking (CSS) change.
