### ISSUE TITLE
Run `playwright test` on every PR push

### ISSUE THREAD

**Issue by pacocoursey** [pacocoursey/cmdk#24]
We should set up a GitHub action to test changes made in every PR via the existing Playwright setup. Would complement nicely with the Vercel deployment.

**Comment by bk973** [comment]
New to open source and seeking any opportunity to contribute to react community. Is this a good issue I can start with?

**Comment by Jak2k** [comment]
Just add playwright to your `package.json` as `test`.
Then ylu can use the template by github.
