### ISSUE TITLE
is it possible to search by label not by value only?

### ISSUE THREAD

**Issue by bizmich** [pacocoursey/cmdk#240]

**Comment by IlirEdis** [comment]
need this also!

**Comment by najdic** [comment]
@bizmich @IlirEdis have you tried the keywords feature? 🤔 

```tsx
<Command.Item keywords={['fruit', 'apple']}>Apple</Command.Item>
```

If not you can always write custom logic for filtering/searching

```tsx
import { matchSorter } from 'match-sorter';

export function useMatchByLabelAndValue(data, query) {
  return useMemo(
    () => matchSorter(data, query, { keys: ['label', 'value'] }),
    [data, query, keys],
  );
}

function CustomCmdk({ data }) {
    const [searchQuery, setSearchQuery] = useState('');
    const matches = useMatchByLabelAndValue(data, searchQuery);

    return (
      <Command shouldFilter={false}>
        <CommandInput
          value={searchQuery}
          onValueChange={(value) =>
            startTransition(() => setSearchQuery(value))
          }
        />

        <CommandList>
          <CommandEmpty>No results found.</CommandEmpty>

          {matches.map((item) => (
            <CommandItem
              key={item.value}
              onSelect={() => {
                startTransition(() => setSearchQuery(''));
              }}
            >
              <span>
                {item.label} {item.value}
              </span> 
            </CommandItem>
          ))}
        </CommandList>
      </Command>
)}
```

**Comment by shomyx** [comment]
> I notice that when I'm using different value and label as below
> 
> ```
> const options = [
> { value: 1, label: "one" },
> { value: 2, label: "two" }
> }
> ```
> 
> CombBox only search for value, how to to search base on value and label?

Use the custom filter option and combine `value` and `label` as value for the CommandItem(s).

```
<Command
    filter={(value, search) => {
      if (value.includes(search)) return 1;
      return 0;
    }}
>
```

```
<CommandItem value={`${option.value} ${option.label}`}>
```

https://github.com/pacocoursey/cmdk/tree/v1.0.0?tab=readme-ov-file#parts-and-styling

![Screenshot 2024-03-20 at 14 51 26](https://github.com/shadcn-ui/ui/assets/50664399/eb973f39-4ab8-4a55-a0f3-b66ff7268766)

**Comment by IlirEdis** [comment]
I also noticed that if you don't provide a `value` prop it uses the "label" from inside the `<CommandItem>` tag.

Also @najdic & @shomyx thanks a lot for these valuable informations! 
Its my second time using cmdk and i will use these to make searching experience better.

**Comment by bizmich** [comment]
> @bizmich @IlirEdis have you tried the keywords feature? 🤔
> 
> ```tsx
> <Command.Item keywords={['fruit', 'apple']}>Apple</Command.Item>
> ```
> 
> If not you can always write custom logic for filtering/searching
> 
> ```tsx
> import { matchSorter } from 'match-sorter';
> 
> export function useMatchByLabelAndValue(data, query) {
>   return useMemo(
>     () => matchSorter(data, query, { keys: ['label', 'value'] }),
>     [data, query],
>   );
> }
> 
> function CustomCmdk({ data }) {
>     const [searchQuery, setSearchQuery] = useState('');
>     const matches = useMatchByLabelAndValue(data, searchQuery);
> 
>     return (
>       <Command shouldFilter={false}>
>         <CommandInput
>           value={searchQuery}
>           onValueChange={(value) =>
>             startTransition(() => setSearchQuery(value))
>           }
>         />
> 
>         <CommandList>
>           <CommandEmpty>No results found.</CommandEmpty>
> 
>           {matches.map((item) => (
>             <CommandItem
>               key={item.value}
>               onSelect={() => {
>                 startTransition(() => setSearchQuery(''));
>               }}
>             >
>               <span>
>                 {item.label} {item.value}
>               </span> 
>             </CommandItem>
>           ))}
>         </CommandList>
>       </Command>
> )}
> ```

Doesn't it seem illogical to have a filter based on a value that the user cannot see? What's the purpose behind this design?

**Comment by bizmich** [comment]
> Use the custom filter option and combine `value` and `label` as value for the CommandItem(s).
> 
> ```
> <Command
>     filter={(value, search) => {
>       if (value.includes(search)) return 1;
>       return 0;
>     }}
> >
> ```
> 
> ```
> <CommandItem value={`${option.value} ${option.label}`}>
> ```
> 
> https://github.com/pacocoursey/cmdk/tree/v1.0.0?tab=readme-ov-file#parts-and-styling
> 
> ![Screenshot 2024-03-20 at 14 51 26](https://private-user-images.githubusercontent.com/50664399/314524848-eb973f39-4ab8-4a55-a0f3-b66ff7268766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzg3NTIsIm5iZiI6MTcxMjMzODQ1MiwicGF0aCI6Ii81MDY2NDM5OS8zMTQ1MjQ4NDgtZWI5NzNmMzktNGFiOC00YTU1LWEwZjMtYjY2ZmY3MjY4NzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE3MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjlhNDhlZThhZGZkMWNkZDYyMDZlZmQ2MzlhNDA0NGQ2YzA4ZDMyMjQwMGU1N2VjMDZjYjNiNzNiZDMzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fmKeMyNhbGpbNwkH3mWZaaxD5KA5tTIJomjCl29nw38)

After combining label and value, I get both results. This makes me  filter the output again. Is there a more efficient way to do this?
