### ISSUE TITLE
'querySelector' on 'Element': '[cmdk-item=""][data-value=""]' is not a valid selector

### ISSUE THREAD

**Issue by capkakitiga** [pacocoursey/cmdk#242]
I have Item content like this

<img width="429" alt="image" src="https://github.com/pacocoursey/cmdk/assets/85972369/fa33f984-0378-47c7-9f74-806ee3b3247b">

But in the production it's causing error like this

<img width="495" alt="image" src="https://github.com/pacocoursey/cmdk/assets/85972369/05d3babc-c688-423f-aa5f-5033b9ef0a3d">
 
Any idea whats happened?

**Comment by pacocoursey** [comment]
You should provide a `value` to the `Command.Item`.
