### ISSUE TITLE
Disabled options with shadcn implementation on 1.0.0

### ISSUE THREAD

**Issue by jatinahluwalia** [pacocoursey/cmdk#245]
The options are greyed out and disabled (onSelect doesn't get called on mouse click) when using with version 1.0.0. However, everything fine on 0.2.0

**Comment by sipos-david** [comment]
Hey @jatinahluwalia, this is becase 1.0.0 ads `data-disabled=false` with `well aria-disabled` (source https://github.com/pacocoursey/cmdk/commit/c57e6b7f81a5796395c7a016d6b1b2aac9591973), however shadcn relies on the old behavior in the css:

`data-[disabled]:pointer-events-none data-[disabled]:opacity-50`
 To fix this change the attribute selectors to:
 `data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50`

You need to do this in the **CommandItem** shadcn component, by default this is located in `components/ui/command.tsx`
