### ISSUE TITLE
Add Link component

### ISSUE THREAD

**Issue by arjendevos** [pacocoursey/cmdk#258]
Currently I can add a Link component like this:
```ts
<CommandItem variant="muted">
  <Link className="grow" href="/settings">
    <Cog6ToothIcon className="mr-2 size-4" />
    settings
  </Link>
</CommandItem>
```

However I have a few requests:
- Use the child component as main one, so I can apply the same styling to the Link component (asChild)
- Propagate the onSelect with to an onClick to the child component (or asChild^)

**Comment by Willem-Jaap** [comment]
I ran into the same issue, currently I do this: 
![image](https://github.com/pacocoursey/cmdk/assets/67187467/c62dc70f-fb8d-4ef5-a1ff-70402b6378d8)

I read in https://github.com/pacocoursey/cmdk/blob/main/ARCHITECTURE.md you don't want to support render props. this is just an idea but maybe you can provide an `as` prop for passing custom link components like `next/link`
![image](https://github.com/pacocoursey/cmdk/assets/67187467/e7bc169a-ea96-4815-990b-b7fe39255210)
