### ISSUE TITLE
How to focus on the last element by ArrowUp click?

### ISSUE THREAD

**Issue by ghost** [pacocoursey/cmdk#259]
When the cmdk dialog pops up, it has focus on the first Command Item and with arrowDown you can focus on the 2nd and so on..
But when I press arrowUp, I would love to focus on the last command item on the list.

Also is there way of not having focus on the first item by default when the dialog opens? Thanks

**Comment by davidmokos** [comment]
Pass in `loop` prop into the Command like `<Command loop />`. This will move your cursor to the last item when you press arrow up
