### ISSUE TITLE
Sometimes cannot go down with down arrow

### ISSUE THREAD

**Issue by bsansouci** [pacocoursey/cmdk#26]
Hey all, thanks for making this. I was playing around with the demo on the website and found two bugs that I'll lump in one here.
First if I go to the Framer example and type "baa", then delete the last "a", the only result showing is not highlighted which seems like a bug to me. However I can highlight it by going down with the down arrow.
 
Then if I delete another "a", I see two results, but I cannot go up/down with the arrows anymore.

Here's a video where I'm pressing up/down arrow at the end.

https://user-images.githubusercontent.com/4534692/183738721-7e2a009e-c38e-484d-808c-e1f3e369868d.mov

**Comment by pacocoursey** [comment]
Thanks for the report, was able to reproduce and trace it back to a change made recently.

Should be fixed in #27 and on this preview: 
https://cmdk-website-git-paco-fix-unstable-ids-paco.vercel.app
