### ISSUE TITLE
Extract Group.Heading to a separate component

### ISSUE THREAD

**Issue by JonathanLorimer** [pacocoursey/cmdk#261]
Things like vanilla extract don't support styling arbitrary children using complex selectors like data selectors. It would be great to have an escape hatch and be able to pass your own class to certain components (like group headers).

Here is the discussion I started in the vanilla extract repo https://github.com/vanilla-extract-css/vanilla-extract/discussions/1411

**Comment by pacocoursey** [comment]
Agreed. A future update will make the Group header a separate component that forwards `className`.
