### ISSUE TITLE
Link github repo in npm

### ISSUE THREAD

**Issue by batmot** [pacocoursey/cmdk#262]
Hello ! 

The repository is not linked in npm because the package is a module in a monorepo. The directory must be set. 

In : `cmdk/package.json`

```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/pacocoursey/cmdk.git",
    "directory": "cmdk"
  },
  ```
  
  This will permit to get the link to the repo on npm and this should increase the score of the package on [Snyk](https://snyk.io/advisor/npm-package/cmdk) 🚀 
  
  It seems I haven't rights to push the changes on a branch 😕

**Comment by tforssell** [comment]
Hi,
This issue is not closed, and the Snyk score is still affected.
Perhaps the "repository" field should be specified in the root package.json.
