### ISSUE TITLE
feature request: ability to have nested groups

### ISSUE THREAD

**Issue by danyadanch** [pacocoursey/cmdk#275]
To be honest now we can have nested `Command.Group`, but results of 2nd group is not searchable.  

``` tsx
<Command.List>
   <Command.Group heading="Parent">
      <Command.Group heading="Child">
        <Command.Item>You can't find me</Command.Item>
      </Command.Group>
      <Command.Item>You can find me</Command.Item>
   </Command.Group>
</Command.List>

**Comment by ringcrl** [comment]
! [image] (https://github.com/pacocoursey/cmdk/assets/16740021/4773715f-6c68-4efc-bd12-2fbf5cee4f7e)

Similar issue, want to provide a secondary menu like Notion AI, and allow search

The search results are as follows:
![image](https://github.com/pacocoursey/cmdk/assets/16740021/60124105-b9d3-44ab-a6d7-b921f5416d22)
