### ISSUE TITLE
Command.Group is causing an error

### ISSUE THREAD

**Issue by verdverm** [pacocoursey/cmdk#284]
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

Using the example from the Readme: https://github.com/pacocoursey/cmdk?tab=readme-ov-file#use-inside-popover

Replace `List` with `Group`

Let me know if you need version information or any more details!

Super cool component btw!

**Comment by verdverm** [comment]
On an aside, I cannot click items under `Command.List`, is this expected?

**Comment by tparrishbard** [comment]
I'm experiencing the same issue

**Comment by lautaro012** [comment]
Same problem here.

**Comment by lautaro012** [comment]
https://github.com/pacocoursey/cmdk/issues/244 This worked for me guys.

**Comment by verdverm** [comment]
@pacocoursey

Why did you close this as complete? I have this error without the use of `shadcn`, with the example from the README, with `s/List/Group/`. The linked issue does not resolve

**Comment by arnaudambro** [comment]
yes, List works, not Group
