### ISSUE TITLE
Ussing shadcn, CommandItem classes causes the item to be disabled, cmdk v.1.0.0

### ISSUE THREAD

**Issue by jhomudev** [pacocoursey/cmdk#285]
When adding the command component to my project, and using it, the styles of the list items occupy **"disabled" styles**.

![image](https://github.com/user-attachments/assets/834a59e2-1760-4b12-8a90-78589da0f57c)

Which was fixed by setting them **true**:

![image](https://github.com/user-attachments/assets/a2be3c6c-c469-44f4-a984-5f2744fe1266)

I also saw that when using this component inside the **shadcn sheet component**, it **inherits the style of "pointer-events: none;"** from body tag

**Comment by mehul-lega** [comment]
Having the same issue.

**Comment by gastbob40** [comment]
Hey,

I also have this issue

**Comment by jhomudev** [comment]
The "pointer-events: none" style using the shadcn sheet component was solved in my case by deleting the **package.lock.json** file and the **node modules folder** and running `npm install` again

**Comment by joseglego** [comment]
Hey, somebody already reported this issue: https://github.com/pacocoursey/cmdk/issues/245

They came to a different solution, which is pretty simple: https://github.com/pacocoursey/cmdk/issues/245#issuecomment-2031580824.
