### ISSUE TITLE
Searching returns incorrect results

### ISSUE THREAD

**Issue by dynjo** [pacocoursey/cmdk#303]
To reproduce, go to [https://cmdk.paco.me](https://cmdk.paco.me) and type `x`

Result list shows "Figma" which does not contain an `x`

**Comment by rollsrobby** [comment]
figma has a keyword for "ux" which is why it is returned when you search for "x". So I guess this is expected.

```tsx
...
<Item value="Figma" keywords={['design', 'ui', 'ux']}>
  <Logo>
    <FigmaIcon />
  </Logo>
  Figma
</Item>
...
```

[Link to source](https://github.com/pacocoursey/cmdk/blob/92344c58a63b995f6eb149245c56ea548540dd18/website/components/cmdk/raycast.tsx#L37)

**Comment by rollsrobby** [comment]
I guess that has to do with the filtering algorithm that is not as straight forward as a substring search.

[command-score](https://github.com/pacocoursey/cmdk/blob/92344c58a63b995f6eb149245c56ea548540dd18/cmdk/src/command-score.ts)
