### ISSUE TITLE
Open-source styling used on homepage?

### ISSUE THREAD

**Issue by heymartinadams** [pacocoursey/cmdk#37]
I’d like to use the styling you’ve used on your [homepage](https://cmdk.paco.me/) (for Raycast) — would I be able to? If yes, how?

Thank you ✨

**Comment by raunofreiberg** [comment]
All styles for the homepage are located under [website/styles/index.module.scss](https://github.com/pacocoursey/cmdk/blob/main/website/styles/index.module.scss).
