### ISSUE TITLE
Not working on NextJS

### ISSUE THREAD

**Issue by heymartinadams** [pacocoursey/cmdk#38]
Hi @raunofreiberg, for some reason, I’m unable to get it to work on NextJS (using latest `next` and `react`, `react-dom`). I’ve included a basic reproduction here: [cmdk-nextjs](https://github.com/ConsciousApps/cmdk-nextjs).

As you can see below, nothing happens. I must be missing something basic, but have no idea what I’m missing.

![CleanShot 2022-08-17 at 08 47 58](https://user-images.githubusercontent.com/11673745/185184622-d806c7a7-bf52-4ffb-9c12-c94605f624f7.gif)

**Comment by pacocoursey** [comment]
You're putting a Dialog inside of a Popover, and the dialog is always closed. You should just use the regular `Command` component:

```tsx
<Popover.Content>
  <Command>
    ...
  </Command>
</Popover.Content>
```
