### ISSUE TITLE
Command.Dialog search function does not work as expected

### ISSUE THREAD

**Issue by Beckem** [pacocoursey/cmdk#40]
When type backspace filter results do not update. This issue also exists for example on https://cmdk.paco.me/

**Comment by pacocoursey** [comment]
Can you share a more specific example? Pressing [Backspace] completely works for me.

**Comment by Beckem** [comment]
> Can you share a more specific example? Pressing [Backspace] completely works for me.

https://drive.google.com/file/d/10FZiUymNjKMUzKl8-zSZm-Sut0seKZSr/view?usp=sharing
When press [Backspace] to show the filter result must appear like when you type show

**Comment by pacocoursey** [comment]
Hmm weird, will take a closer look.

**Comment by manuthecoder** [comment]
I also noticed this issue when trying to implement this in my web app

**Comment by caumeira** [comment]
> > Can you share a more specific example? Pressing [Backspace] completely works for me.
> 
> https://drive.google.com/file/d/10FZiUymNjKMUzKl8-zSZm-Sut0seKZSr/view?usp=sharing When press [Backspace] to "show" the filter result must appear like when you type show



> I also noticed this issue when trying to implement this in my web app

Passing value prop to item fix the inssue for me:
 ```<Command.Item value="textValue">textValue</Command.Item>```
