### ISSUE TITLE
Error when using useCommandState

### ISSUE THREAD

**Issue by mrmartineau** [pacocoursey/cmdk#54]
I have just added `useCommandState` to my cmdk component and before anything is even typed this error is shown. I am using the latest version of next.js (v12.3.1), React (v18.2.0) and cmdk (v0.1.20). Do you have any idea why this might be occurring? Is there anything else that I need to add in order for this to work?

### Usage
```ts
const search = useCommandState((state) => state.search)
```

### Error
```
TypeError: Cannot read properties of undefined (reading 'subscribe')
```

**Comment by joaom00** [comment]
The `useCommandState` hook must be used below the `Command` component

**Comment by mrmartineau** [comment]
Thanks @joaom00, the docs do not state that this hook relates to React context.
