### ISSUE TITLE
How to make SubItem render other items

### ISSUE THREAD

**Issue by Mbensler** [pacocoursey/cmdk#66]
I am trying to make my SubItem render something like this:
```js
{searchItems.map(({ icon, label }) => {
    return (
        <SubItem key={label}>
            <div>
                <img src={icon} />
                <p>{label}</p>
            </div>
        </SubItem>;
    )
})}
```
But it won´t work like this.

It will only work when it looks like this: 
```js
{searchItems.map(({ icon, label }) => {
    return 
        <SubItem key={label}>
            {label}
        </SubItem>;
})}
```
Then it shows up correctly. If I were to do `{icon} {label}` it doesn't work either.

It seems like it only accepts one thing, and I am trying to get it to look like a normal `Command.Item` with an icon on the left and text next to it without a shortcut.

**Comment by pacocoursey** [comment]
I don't fully understand your question without a minimal reproduction, but please try passing a unique `value` prop to each `Command.Item` to ensure everything works as expected. Then report back :)

**Comment by Mbensler** [comment]
I was missing the value prop. It works now. Thank you very much.
