### ISSUE TITLE
Enable className on the `Overlay` and `Root`

### ISSUE THREAD

**Issue by Kinbaum** [pacocoursey/cmdk#69]
Can we expose the Overlay and Root elements and manually implement them, or be able to pass in a className for custom styling? This will make styling simpler with frameworks like tailwind

https://github.com/pacocoursey/cmdk/blob/605ae1304baff5ed6f7675d6028ad8dc0b93f0ca/cmdk/src/index.tsx#L779-L786

**Comment by SukkaW** [comment]
+1 on this.

@pacocoursey I can open a PR and add `overlayClassName` and `rootClassName` to the props. I'd like to know what you think about these props.

(Personally, I'd prefer adding overlay through `Command.Overlay`, but it would be a breaking change.)
