### ISSUE TITLE
Use cmdk for Chrome Extension

### ISSUE THREAD

**Issue by rebryk** [pacocoursey/cmdk#71]
I am trying to add `cmdk` for the react-based chrome extension. 
But `Command.Dialog` appears at the end of the page without any styling.

For example, how it looks on github.com:
<img width="594" alt="209028806-dd553769-fdd4-4f55-95ec-0f343226f8bf" src="https://user-images.githubusercontent.com/4231665/209029113-0ee656f4-2400-417b-96cf-740b2dca44bb.png">

Do you have any idea what went wrong?

**Comment by raunofreiberg** [comment]
The component is unstyled out of the box for customization. You can copy and paste styles as a starting point from [here](https://github.com/pacocoursey/cmdk#drop-in-stylesheets).
