### ISSUE TITLE
Create New

### ISSUE THREAD

**Issue by emersonlaurentino** [pacocoursey/cmdk#75]
It would be really cool if there were no result, just as it is possible to render `Command.Empty` there was also a `Command.Create` that could render a selected Item with the message `Create new "${seach}"`.

I tried to do this, however, the `Command.Item` is rendered null when there are no filtered results.

https://github.com/pacocoursey/cmdk/blob/a7c974083d8b201f39dc5a340a65ae8472781574/cmdk/src/index.tsx#L603

Como seria legal que fosse

Proposal 1

```tsx
<Command>
  <Command.Input />
  <Command.List>
    <Command.Item>Apple</Command.Item>
    <Command.Item create>Create New</Command.Item>
  </Command.List>
</Command>
```

`Command.Item create` would only be displayed when the filter count was 0 (like Command.Empty).

Proposal 2

```tsx
<Command>
  <Command.Input />
  <Command.List>
    <Command.Item>Apple</Command.Item>
    <Command.Create>Create New</Command.Create>
  </Command.List>
</Command>
```

`Command.Create` would only be displayed when the filter count was 0 (like Command.Empty).

**Comment by raunofreiberg** [comment]
Hi.

Have you tried rendering a `Command.Item` where the `value` is the current input value?

```tsx
<Command>
  <Command.Input value={inputValue} onChange={e => setInputValue(e.target.value)} />
  <Command.List>
    <Command.Item value={inputValue} onSelect={createNew}>
       Create new {inputValue}
    </Command.Item>
  </Command.List>
</Command>
```

This way it should always match the input query and even show up when no other results are matching.

**Comment by pacocoursey** [comment]
You may also wish to use the (advanced) [`useCommandState` hook documented here](https://github.com/pacocoursey/cmdk#usecommandstatestate--stateselectedfield):

```tsx
const search = useCommandState((state) => state.search)
const isEmpty = useCommandState((state) => state.filtered.count === 0)
```

**Comment by emersonlaurentino** [comment]
> You may also wish to use the (advanced) [`useCommandState` hook documented here](https://github.com/pacocoursey/cmdk#usecommandstatestate--stateselectedfield):
> 
> ```tsx
> const search = useCommandState((state) => state.search)
> const isEmpty = useCommandState((state) => state.filtered.count === 0)
> ```

I tried that way, but I couldn't render the `Command.Item` anyway.

**Comment by emersonlaurentino** [comment]
> Have you tried rendering a Command.Item where the value is the current input value?

I'll test this approach.

**Comment by emersonlaurentino** [comment]
@raunofreiberg it worked, however when I search for something that ends with a space, the count goes to 0, thus removing the create new button.

So a strange behavior is when I search for a compound name it keeps blinking every space. Example:

```
"rauno" = true
"rauno " = false
"rauno f" = true
```

**Comment by Gm33** [comment]
Any updates on this? @vainamov even with your suggested solution, the empty screen keeps popping up with a space

**Comment by TmLev** [comment]
It's the third time this week I've encountered this problem and I still have no good solution in mind. Sometimes it just works, sometimes it doesn't.

**Comment by cah4a** [comment]
Got this working using:

```tsx
<Command
   filter={(item, query) => {
      if (item === "+create+") {
         return 1;
      }
      if (item.toLowerCase().includes(query.trim().toLowerCase())) {
         return 1;
      }
      return 0;
   }}
>
```

and 

```tsx
const CommandCreateItem = ({ onSelect }: { onSelect: (value: string) => void }) => {
   const query = useCommandState((state) => state.search);
   if (!query || !onCreate) return null;
   return (
      <CommandItem
         forceMount
         value="+create+"
         onSelect={() => onSelect(query)}
      >
         <MdAdd className="mr-2" /> {query}
      </CommandItem>
   );
});
```

**Comment by andrioidApacta** [comment]
I'm also having this issue. Passing `search` as the value causes React 18 to freak out with too many state changes. Ironically, that only happens inside of `<Command.Empty>` - the one inside List doesn't seem to mind.

If I create a new component without using `Command.Item` then keyboard navigation breaks.

Has anyone managed to get this working?

**Comment by Nithur-M** [comment]
Hi
Any updates on this?

It would be cool to have the ability to create custom items when no items available. @raunofreiberg's solution exhibits a weird behavior where it appear intermittently.

**Comment by chrisgrabinski** [comment]
For anyone struggling with this same problem, try this:

```tsx
import { Command, useCommandState } from 'cmdk';

const CreateItem = () => {
  const search = useCommandState((state) => state.search);
  const filtered = useCommandState((state) => state.filtered);

  if (!search || !!filtered.count) {
    return null;
  }

  return <Command.Item forceMount value={search}>Create {search}</Command.Item>
}

const Combobox = {
  return (
    <Command>
      <Command.Input />
      <Command.List>
        <Command.Item>Foo</Command.Item>
        <Command.Item>Bar</Command.Item>
        <CreateItem />
      </Command.List>
    </Command>
  )
}
```

We can use `forceMount` on `Command.Item` to prevent it from being filtered out and control visibility based on the search query.
