### ISSUE TITLE
[Convention] Refactoring Project structure

### ISSUE THREAD

**Issue by Saintpreston** [pacocoursey/cmdk#78]
Is there value in refactoring the [`src`](https://github.com/pacocoursey/cmdk/blob/main/cmdk/src/index.tsx) directory into a more standard project structure since it's approaching 1000 lines of code

Something along the lines of
```
src/
├── types
├── index
├── hooks/
│   ├── types
│   └── useLazyRef
├── store/
│   ├── types
│   ├── index
│   └── contexts
└── constants/
    └── index
```

I'd be willing to begin breaking this down to smaller tasks and migrating to if there's an interest

**Comment by pacocoursey** [comment]
Hey Preston, thanks for the offer!

I'd say that's just busy work, though, and doesn't add much value. 1,000 lines is still pretty small. If it grows substantially (🤞 hope not) then we can reconsider.

**Comment by Saintpreston** [comment]
👍 :) np
