### ISSUE TITLE
How do I force dark mode?

### ISSUE THREAD

**Issue by talksik** [pacocoursey/cmdk#94]
My app doesn't support light mode. How can I prevent the styles being dynamic?

I was thinking there would be some prop for theme override.

**Comment by talksik** [comment]
If I use some of the given stylesheets, won't it be styled?

**Comment by pacocoursey** [comment]
Ah yes, it will. You should just remove the light-mode specific CSS from the stylesheet you're copying in, or wrap your container with `.dark` so that dark mode styles are always applied.

**Comment by talksik** [comment]
Awesome thank you for that! Appreciate it!
